import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";
import ThemeToggle from "@/components/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "PaperPilot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
        <header className="app-header">
          <div className="container">
            <nav className="navbar">
              <div className="nav-brand">
                <h1>PaperPilot</h1>
              </div>
              <div className="nav-controls">
                <ThemeToggle />
              </div>
            </nav>
          </div>
        </header>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
